FROM python:3.9

# directory_path = os.path.dirname(__file__)
# path = os.path.join(directory_path, "src")

ADD src .

# RUN pip install matplotlib plotly_express pandas numpy dash sklearn

CMD ["python", "./src/ex1_0_setup.py"]
