services:
  python:
    # image: python:3.11
    build: . #check in the docker file from same directory and build from there
    ports: 
      - "8050:8050"
    container_name: lecture2
  
    # named volume
    volumes:
      - dice_simulator:/app/src/

volumes:
  dice_simulator: