FROM python:3.9

# directory_path = os.path.dirname(__file__)
# path = os.path.join(directory_path, "src")

ADD Exercise2 .

RUN pip install matplotlib plotly_express pandas numpy dash sklearn beautifulsoup4

# CMD ["python", "./ex1_1_setup.py"]
